<?php

namespace Database\Seeders;

use App\Models\Coa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CoaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coas = [
            // PT
            ['code' => 'PT-101', 'name' => 'Kas', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-101.1', 'name' => 'AYS Kas/Bank', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-102', 'name' => 'Bank', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-103', 'name' => 'Piutang usaha', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-104', 'name' => 'Penyisihan piutang usaha', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-105', 'name' => 'Perlengkapan', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-106', 'name' => 'Sewa dibayar dimuka', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-107', 'name' => 'Asuransi dibayar dimuka', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-108', 'name' => 'Pajak Dibayar di Muka', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-108.1', 'name' => 'PPh 23', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-108.2', 'name' => 'PPh 25', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-108.3', 'name' => 'PPh 29', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-109', 'name' => 'Piutang Karyawan', 'group_coa_id' => 10, 'type' => 'pt'],
            ['code' => 'PT-110', 'name' => 'Investasi saham', 'group_coa_id' => 11, 'type' => 'pt'],
            ['code' => 'PT-111', 'name' => 'Investasi obligasi', 'group_coa_id' => 11, 'type' => 'pt'],
            ['code' => 'PT-121', 'name' => 'Tanah', 'group_coa_id' => 12, 'type' => 'pt'],
            ['code' => 'PT-122', 'name' => 'Gedung', 'group_coa_id' => 12, 'type' => 'pt'],
            ['code' => 'PT-123', 'name' => 'Akumulasi penyusutan gedung', 'group_coa_id' => 12, 'type' => 'pt'],
            ['code' => 'PT-124', 'name' => 'Kendaraan', 'group_coa_id' => 12, 'type' => 'pt'],
            ['code' => 'PT-125', 'name' => 'Akumulasi penyusutan kendaraan', 'group_coa_id' => 12, 'type' => 'pt'],
            ['code' => 'PT-126', 'name' => 'Peralatan', 'group_coa_id' => 12, 'type' => 'pt'],
            ['code' => 'PT-127', 'name' => 'Akumulasi Penyusutan Peralatan', 'group_coa_id' => 12, 'type' => 'pt'],
            ['code' => 'PT-201', 'name' => 'Utang usaha', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-202', 'name' => 'Beban yang masih harus dibayar', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-203', 'name' => 'Utang gaji', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-204', 'name' => 'Utang sewa gedung', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-205', 'name' => 'Utang pajak penghasilan', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-205.1', 'name' => 'Utang PPh21', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-205.2', 'name' => 'Utang PPh23', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-205.3', 'name' => 'Utang Biaya', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-206', 'name' => 'Utang pihak lain', 'group_coa_id' => 20, 'type' => 'pt'],
            ['code' => 'PT-211', 'name' => 'Utang Bank', 'group_coa_id' => 21, 'type' => 'pt'],
            ['code' => 'PT-301', 'name' => 'Modal', 'group_coa_id' => 30, 'type' => 'pt'],
            ['code' => 'PT-302', 'name' => 'Saldo laba ditahan', 'group_coa_id' => 30, 'type' => 'pt'],
            ['code' => 'PT-303', 'name' => 'Dividen', 'group_coa_id' => 30, 'type' => 'pt'],
            ['code' => 'PT-304', 'name' => 'Prive', 'group_coa_id' => 30, 'type' => 'pt'],
            ['code' => 'PT-305', 'name' => 'Laba (Rugi) Periode Berjalan', 'group_coa_id' => 30, 'type' => 'pt'],
            ['code' => 'PT-401', 'name' => 'Pendapatan usaha/Fee Bulanan', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-401.1', 'name' => 'Pendapatan usaha/Fee SPT', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-401.2', 'name' => 'Pendapatan usaha/Fee SP2DK', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-401.3', 'name' => 'Pendapatan usaha/Fee Pembetulan', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-401.4', 'name' => 'Pendapatan usaha/Fee Internal', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-401.5', 'name' => 'Pendapatan usaha/Fee Restitusi', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-401.6', 'name' => 'Pendapatan usaha/Fee Pemeriksaan', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-410', 'name' => 'Pendapatan Lain-lain', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-410.1', 'name' => 'Pendapatan Bunga', 'group_coa_id' => 40, 'type' => 'pt'],
            ['code' => 'PT-501', 'name' => 'Beban gaji', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-501.1', 'name' => 'Beban Konsultan', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-501.2', 'name' => 'Beban THR', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-502', 'name' => 'Beban sewa gedung', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-503', 'name' => 'Beban perlengkapan kantor', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-504', 'name' => 'Beban Pelatihan', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-505', 'name' => 'Beban ATK', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-506', 'name' => 'Beban Internet dan Telepon', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-507', 'name' => 'Beban Air dan Listrik', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-508', 'name' => 'Beban Transport', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-509', 'name' => 'Beban penyusutan', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-510', 'name' => 'Beban bunga', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-511', 'name' => 'Beban Admin', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-512', 'name' => 'Beban Operasional', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-513', 'name' => 'BPJS Kesehatan', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-514', 'name' => 'BPJS Jamsostek', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-514.1', 'name' => 'BPJS Jamsostek - JKK JKM', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-514.2', 'name' => 'BPJS Jamsostek - JHT JKP', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-515', 'name' => 'Beban PPh Final', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-516', 'name' => 'Beban Pengiriman', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-517', 'name' => 'Beban Sewa Kendaraan', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-518', 'name' => 'PPh 21', 'group_coa_id' => 50, 'type' => 'pt'],
            ['code' => 'PT-600', 'name' => 'Beban Luar Usaha', 'group_coa_id' => 60, 'type' => 'pt'],
            ['code' => 'PT-601', 'name' => 'Beban administrasi bank', 'group_coa_id' => 60, 'type' => 'pt'],
            ['code' => 'PT-602', 'name' => 'Rugi penjualan Aset', 'group_coa_id' => 70, 'type' => 'pt'],
            ['code' => 'PT-603', 'name' => 'Kesalahan Transfer', 'group_coa_id' => 70, 'type' => 'pt'],
            ['code' => 'PT-700', 'name' => 'Pendapatan Luar Usaha', 'group_coa_id' => 70, 'type' => 'pt'],
            ['code' => 'PT-701', 'name' => 'Pendapatan Jasa Giro', 'group_coa_id' => 70, 'type' => 'pt'],
            ['code' => 'PT-702', 'name' => 'Laba Penjualan Aset', 'group_coa_id' => 70, 'type' => 'pt'],
            ['code' => 'PT-703', 'name' => 'Pendapatan bunga', 'group_coa_id' => 70, 'type' => 'pt'],
            // AO
            ['code' => 'AO-101', 'name' => 'Kas', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-101.1', 'name' => 'AYS Kas/Bank', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-102', 'name' => 'Bank', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-103', 'name' => 'Piutang usaha', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-104', 'name' => 'Penyisihan piutang usaha', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-105', 'name' => 'Perlengkapan', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-106', 'name' => 'Sewa dibayar dimuka', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-107', 'name' => 'Asuransi dibayar dimuka', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-108', 'name' => 'Pajak Dibayar di Muka', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-108.1', 'name' => 'PPh 23', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-108.2', 'name' => 'PPh 25', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-108.3', 'name' => 'PPh 29', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-109', 'name' => 'Piutang Karyawan', 'group_coa_id' => 10, 'type' => 'kkp'],
            ['code' => 'AO-111', 'name' => 'Investasi saham', 'group_coa_id' => 11, 'type' => 'kkp'],
            ['code' => 'AO-112', 'name' => 'Investasi obligasi', 'group_coa_id' => 11, 'type' => 'kkp'],
            ['code' => 'AO-121', 'name' => 'Tanah', 'group_coa_id' => 12, 'type' => 'kkp'],
            ['code' => 'AO-122', 'name' => 'Gedung', 'group_coa_id' => 12, 'type' => 'kkp'],
            ['code' => 'AO-123', 'name' => 'Akumulasi penyusutan gedung', 'group_coa_id' => 12, 'type' => 'kkp'],
            ['code' => 'AO-124', 'name' => 'Kendaraan', 'group_coa_id' => 12, 'type' => 'kkp'],
            ['code' => 'AO-125', 'name' => 'Akumulasi penyusutan kendaraan', 'group_coa_id' => 12, 'type' => 'kkp'],
            ['code' => 'AO-126', 'name' => 'Peralatan', 'group_coa_id' => 12, 'type' => 'kkp'],
            ['code' => 'AO-127', 'name' => 'Akumulasi Penyusutan Peralatan', 'group_coa_id' => 12, 'type' => 'kkp'],
            ['code' => 'AO-201', 'name' => 'Utang usaha', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-202', 'name' => 'Beban yang masih harus dibayar', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-203', 'name' => 'Utang gaji', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-204', 'name' => 'Utang sewa gedung', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-205', 'name' => 'Utang pajak penghasilan', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-205.1', 'name' => 'Utang PPh21', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-205.2', 'name' => 'Utang PPh23', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-205.3', 'name' => 'Utang PPh29', 'group_coa_id' => 20, 'type' => 'kkp'],
            ['code' => 'AO-206', 'name' => 'Utang pihak lain', 'group_coa_id' => 21, 'type' => 'kkp'],
            ['code' => 'AO-211', 'name' => 'Utang Bank', 'group_coa_id' => 21, 'type' => 'kkp'],
            ['code' => 'AO-301', 'name' => 'Modal', 'group_coa_id' => 30, 'type' => 'kkp'],
            ['code' => 'AO-302', 'name' => 'Saldo laba ditahan', 'group_coa_id' => 30, 'type' => 'kkp'],
            ['code' => 'AO-303', 'name' => 'Dividen', 'group_coa_id' => 30, 'type' => 'kkp'],
            ['code' => 'AO-304', 'name' => 'Prive', 'group_coa_id' => 30, 'type' => 'kkp'],
            ['code' => 'AO-305', 'name' => 'Laba (Rugi) Periode Berjalan', 'group_coa_id' => 30, 'type' => 'kkp'],
            ['code' => 'AO-401', 'name' => 'Pendapatan usaha/Fee Bulanan', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-401.1', 'name' => 'Pendapatan usaha/Fee SPT', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-401.2', 'name' => 'Pendapatan usaha/Fee SP2DK', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-401.3', 'name' => 'Pendapatan usaha/Fee Pembetulan', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-401.4', 'name' => 'Pendapatan usaha/Fee Internal', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-401.5', 'name' => 'Pendapatan usaha/Fee Restitusi', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-401.6', 'name' => 'Pendapatan usaha/Fee Pemeriksaan', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-410', 'name' => 'Pendapatan Lain-lain', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-4101', 'name' => 'Pendapatan Bunga', 'group_coa_id' => 40, 'type' => 'kkp'],
            ['code' => 'AO-501', 'name' => 'Beban gaji', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-501.1', 'name' => 'Beban Konsultan', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-501.2', 'name' => 'Beban THR', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-502', 'name' => 'Beban sewa gedung', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-503', 'name' => 'Beban perlengkapan kantor', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-504', 'name' => 'Beban Pelatihan', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-505', 'name' => 'Beban ATK', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-506', 'name' => 'Beban Internet dan Telepon', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-507', 'name' => 'Beban Air dan Listrik', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-508', 'name' => 'Beban Transport', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-509', 'name' => 'Beban penyusutan', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-510', 'name' => 'Beban bunga', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-511', 'name' => 'Beban Admin', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-512', 'name' => 'Beban Operasional', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-513', 'name' => 'BPJS Kesehatan', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-514', 'name' => 'BPJS Jamsostek', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-514.1', 'name' => 'BPJS Jamsostek - JKK JKM', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-514.2', 'name' => 'BPJS Jamsostek - JHT JKP', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-515', 'name' => 'Beban PPh Final', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-516', 'name' => 'Beban Pengiriman', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-517', 'name' => 'Beban Sewa Kendaraan', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-518', 'name' => 'PPh 21', 'group_coa_id' => 50, 'type' => 'kkp'],
            ['code' => 'AO-600', 'name' => 'Beban Luar Usaha', 'group_coa_id' => 60, 'type' => 'kkp'],
            ['code' => 'AO-601', 'name' => 'Beban administrasi bank', 'group_coa_id' => 60, 'type' => 'kkp'],
            ['code' => 'AO-602', 'name' => 'Rugi penjualan Aset', 'group_coa_id' => 70, 'type' => 'kkp'],
            ['code' => 'AO-603', 'name' => 'Kesalahan Transfer', 'group_coa_id' => 70, 'type' => 'kkp'],
            ['code' => 'AO-700', 'name' => 'Pendapatan Luar Usaha', 'group_coa_id' => 70, 'type' => 'kkp'],
            ['code' => 'AO-701', 'name' => 'Pendapatan Jasa Giro', 'group_coa_id' => 70, 'type' => 'kkp'],
            ['code' => 'AO-702', 'name' => 'Laba Penjualan Aset', 'group_coa_id' => 70, 'type' => 'kkp'],
            ['code' => 'AO-703', 'name' => 'Pendapatan bunga', 'group_coa_id' => 70, 'type' => 'kkp'],
        ];

        foreach ($coas as $coa) {
            Coa::create($coa);
        }
    }
}
